project:
  type: website
  execute-dir: project
  render:
    - "*.qmd"
    - "!CONTRIBUTIONG.md"
    - "!LICENSE.md"

website:
  title: "Cancer variant analysis"
  favicon: assets/SIB_logo.svg
  search: true
  page-navigation: true
  navbar:
    background: "#003eaa"
    left:
      - href: index.qmd
        text: Home
      - href: precourse_preparations.qmd
      - href: course_schedule.qmd
      - text: 'Course material'
        menu:
            - href: quality_control.qmd
            - href: variant_calling.qmd
            - href: variant_annotation.qmd 
          
    right:
      - icon: github
        href: https://github.com/sib-swiss/cancer-variants-training/
        aria-label: GitHub
  sidebar:
    logo: assets/SIB_LogoQ_GBv.svg

format:
  html:
    code-link: true
    theme: 
      light:
        - default
        - custom.scss
      dark: 
        - darkly
        - custom-dark.scss
    toc: true
    header-includes: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
      <!-- Cookie Consent & Matomo Tracking -->
      <script src="assets/cookie-consent.js"></script>
      <!-- End Matomo Code -->


execute:
  freeze: auto 
  cache: true
  tidy: true



