---
title: "Precourse preparations"
format:
  html:
    css: styles.css
---

## Prerequisites

### Knowledge / competencies
Participants should have knowledge in NGS techniques, quality control and alignment to a reference genome, and detection of genomic variants from read alignment to variant calling and annotation.  

The competences and knowledge levels required correspond to those taught in courses such as: [NGS - Quality Control, Alignment, Visualisation](https://www.sib.swiss/training/course/20240424_NGSQC) and [NGS-Genome Variant Analysis](https://www.sib.swiss/training/course/20240905_NGSGV). 

Participants should have a basic understanding of working with command line tools on Unix-based systems. You can test your skills with Unix with the quiz [here](https://docs.google.com/forms/d/e/1FAIpQLSd2BEWeOKLbIRGBT_aDEGPce1FOaVYBbhBiaqcaHoBKNB27MQ/viewform?usp=sf_link). If you do not feel comfortable with UNIX commands, please take our [Unix fundamentals](https://edu.sib.swiss/pluginfile.php/2878/mod_resource/content/4/couselab-html/content.html) e-learning module. 

### Technical
Participants should have their own computer with a browser installed (e.g. chrome, firefox, edge), and can access http websites. Test it here: [http://httpforever.com/](http://httpforever.com/).  

### Communication platform
This course will use **Zulip** for communication and questions during the course. You will receive an invitation to join our Zulip workspace before the course starts. Zulip is a chat platform that organizes discussions by topics - no prior experience needed, and it works in any web browser. Zulip can be accessed also via desktop/mobile apps.
